export const CREATE_MESSAGE = "CONTACTS/CREATE_MESSAGE";
export const DELETE_MESSAGE = "CONTACTS/DELETE_MESSAGE";
export const CHAT_OPEN = "CONTACTS/CHAT_OPEN";
export const CHAT_CLOSE = "CONTACTS/CHAT_CLOSE";
export const SEND_MESSAGEF = "CONTACTS/SEND_MESSAGEF";

export const FILTER_ON = "SKILLS/FILTER_ON";
export const FILTER_OFF = "SKILLS/FILTER_OFF";
